// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_school_username_ from "./routes/[school]/[username].tsx";
import * as $_school_index from "./routes/[school]/index.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $accept_invitation from "./routes/accept-invitation.tsx";
import * as $admin_challenges_index from "./routes/admin/challenges/index.tsx";
import * as $admin_classrooms_index from "./routes/admin/classrooms/index.tsx";
import * as $admin_import_index from "./routes/admin/import/index.tsx";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $admin_parents_index from "./routes/admin/parents/index.tsx";
import * as $admin_quota from "./routes/admin/quota.tsx";
import * as $admin_schools_index from "./routes/admin/schools/index.tsx";
import * as $admin_usage from "./routes/admin/usage.tsx";
import * as $admin_users_index from "./routes/admin/users/index.tsx";
import * as $api_admin_bulk_import from "./routes/api/admin/bulk-import.ts";
import * as $api_admin_challenges from "./routes/api/admin/challenges.ts";
import * as $api_admin_check_admins from "./routes/api/admin/check-admins.ts";
import * as $api_admin_classrooms from "./routes/api/admin/classrooms.ts";
import * as $api_admin_delete_cache from "./routes/api/admin/delete-cache.ts";
import * as $api_admin_force_promote from "./routes/api/admin/force-promote.ts";
import * as $api_admin_migrate_users from "./routes/api/admin/migrate-users.ts";
import * as $api_admin_parent_associations from "./routes/api/admin/parent-associations.ts";
import * as $api_admin_promote_first from "./routes/api/admin/promote-first.ts";
import * as $api_admin_quota_stats from "./routes/api/admin/quota-stats.ts";
import * as $api_admin_schools from "./routes/api/admin/schools.ts";
import * as $api_admin_send_invite from "./routes/api/admin/send-invite.ts";
import * as $api_admin_usage from "./routes/api/admin/usage.ts";
import * as $api_admin_users from "./routes/api/admin/users.ts";
import * as $api_admin_validate_cache from "./routes/api/admin/validate-cache.ts";
import * as $api_admin_verify_parent from "./routes/api/admin/verify-parent.ts";
import * as $api_auth_callback from "./routes/api/auth/callback.ts";
import * as $api_auth_complete_setup from "./routes/api/auth/complete-setup.ts";
import * as $api_auth_delegate_signup from "./routes/api/auth/delegate-signup.ts";
import * as $api_auth_forgot_password from "./routes/api/auth/forgot-password.ts";
import * as $api_auth_google_login from "./routes/api/auth/google/login.ts";
import * as $api_auth_login from "./routes/api/auth/login.ts";
import * as $api_auth_logout from "./routes/api/auth/logout.ts";
import * as $api_auth_parent_signup from "./routes/api/auth/parent-signup.ts";
import * as $api_auth_parent_student_verification from "./routes/api/auth/parent-student-verification.ts";
import * as $api_auth_resend_verification from "./routes/api/auth/resend-verification.ts";
import * as $api_auth_reset_password from "./routes/api/auth/reset-password.ts";
import * as $api_auth_signup from "./routes/api/auth/signup.ts";
import * as $api_auth_teacher_signup from "./routes/api/auth/teacher-signup.ts";
import * as $api_auth_update_password from "./routes/api/auth/update-password.ts";
import * as $api_auth_verify from "./routes/api/auth/verify.ts";
import * as $api_challenges_submit from "./routes/api/challenges/submit.ts";
import * as $api_classroom_add from "./routes/api/classroom/add.ts";
import * as $api_classroom_backup_to_sheet from "./routes/api/classroom/backup-to-sheet.ts";
import * as $api_classroom_claim from "./routes/api/classroom/claim.ts";
import * as $api_classroom_export from "./routes/api/classroom/export.ts";
import * as $api_classroom_move_books from "./routes/api/classroom/move-books.ts";
import * as $api_classroom_remove from "./routes/api/classroom/remove.ts";
import * as $api_classroom_update_quantity from "./routes/api/classroom/update-quantity.ts";
import * as $api_debug_list_keys from "./routes/api/debug/list-keys.ts";
import * as $api_debug_me from "./routes/api/debug/me.ts";
import * as $api_debug_my_books from "./routes/api/debug/my-books.ts";
import * as $api_debug_restore_school from "./routes/api/debug/restore-school.ts";
import * as $api_debug_user_by_email from "./routes/api/debug/user-by-email.ts";
import * as $api_delegates_invite_teacher from "./routes/api/delegates/invite-teacher.ts";
import * as $api_delegates_list from "./routes/api/delegates/list.ts";
import * as $api_delegates_remove from "./routes/api/delegates/remove.ts";
import * as $api_invitations_accept from "./routes/api/invitations/accept.ts";
import * as $api_invitations_create from "./routes/api/invitations/create.ts";
import * as $api_invitations_list from "./routes/api/invitations/list.ts";
import * as $api_invitations_revoke from "./routes/api/invitations/revoke.ts";
import * as $api_lookup from "./routes/api/lookup.ts";
import * as $api_school_admin_staff_import from "./routes/api/school-admin/staff-import.ts";
import * as $api_schools from "./routes/api/schools.ts";
import * as $api_settings_update_school from "./routes/api/settings/update-school.ts";
import * as $api_settings_update_sheet_url from "./routes/api/settings/update-sheet-url.ts";
import * as $api_students_claim from "./routes/api/students/claim.ts";
import * as $api_teachers_list from "./routes/api/teachers/list.ts";
import * as $auth_callback from "./routes/auth/callback.ts";
import * as $challenge_book from "./routes/challenge-book.tsx";
import * as $challenge_books from "./routes/challenge-books.tsx";
import * as $claim_classroom from "./routes/claim-classroom.tsx";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $delegate_request from "./routes/delegate-request.tsx";
import * as $delegate_signup from "./routes/delegate-signup.tsx";
import * as $forgot_password from "./routes/forgot-password.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.ts";
import * as $parent_dashboard from "./routes/parent-dashboard.tsx";
import * as $parent_signup from "./routes/parent-signup.tsx";
import * as $parent_claim_students from "./routes/parent/claim-students.tsx";
import * as $reset_password from "./routes/reset-password.tsx";
import * as $school_admin_staff_import_index from "./routes/school-admin/staff-import/index.tsx";
import * as $select_classroom from "./routes/select-classroom.tsx";
import * as $settings from "./routes/settings.tsx";
import * as $setup from "./routes/setup.tsx";
import * as $signup from "./routes/signup.tsx";
import * as $teacher_signup from "./routes/teacher-signup.tsx";
import * as $verify from "./routes/verify.tsx";
import * as $AdminHeader from "./islands/AdminHeader.tsx";
import * as $App from "./islands/App.tsx";
import * as $BarcodeScanner from "./islands/BarcodeScanner.tsx";
import * as $BulkImport from "./islands/BulkImport.tsx";
import * as $ChallengeForm from "./islands/ChallengeForm.tsx";
import * as $ChallengeReview from "./islands/ChallengeReview.tsx";
import * as $ClaimClassroom from "./islands/ClaimClassroom.tsx";
import * as $ClassroomBrowser from "./islands/ClassroomBrowser.tsx";
import * as $DashboardContent from "./islands/DashboardContent.tsx";
import * as $DelegateRequestForm from "./islands/DelegateRequestForm.tsx";
import * as $DelegateSignupForm from "./islands/DelegateSignupForm.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $MultipleChallengeForm from "./islands/MultipleChallengeForm.tsx";
import * as $ParentDashboard from "./islands/ParentDashboard.tsx";
import * as $ParentSignupForm from "./islands/ParentSignupForm.tsx";
import * as $ParentVerification from "./islands/ParentVerification.tsx";
import * as $PublicClassroom from "./islands/PublicClassroom.tsx";
import * as $QuotaMonitor from "./islands/QuotaMonitor.tsx";
import * as $ScanHistory from "./islands/ScanHistory.tsx";
import * as $SchoolCatalog from "./islands/SchoolCatalog.tsx";
import * as $SchoolManagement from "./islands/SchoolManagement.tsx";
import * as $SettingsPanel from "./islands/SettingsPanel.tsx";
import * as $SetupForm from "./islands/SetupForm.tsx";
import * as $SignupForm from "./islands/SignupForm.tsx";
import * as $StaffImport from "./islands/StaffImport.tsx";
import * as $StudentClaimForm from "./islands/StudentClaimForm.tsx";
import * as $TeacherSignupForm from "./islands/TeacherSignupForm.tsx";
import * as $UsageStats from "./islands/UsageStats.tsx";
import * as $UserManagement from "./islands/UserManagement.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[school]/[username].tsx": $_school_username_,
    "./routes/[school]/index.tsx": $_school_index,
    "./routes/_app.tsx": $_app,
    "./routes/accept-invitation.tsx": $accept_invitation,
    "./routes/admin/challenges/index.tsx": $admin_challenges_index,
    "./routes/admin/classrooms/index.tsx": $admin_classrooms_index,
    "./routes/admin/import/index.tsx": $admin_import_index,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/admin/parents/index.tsx": $admin_parents_index,
    "./routes/admin/quota.tsx": $admin_quota,
    "./routes/admin/schools/index.tsx": $admin_schools_index,
    "./routes/admin/usage.tsx": $admin_usage,
    "./routes/admin/users/index.tsx": $admin_users_index,
    "./routes/api/admin/bulk-import.ts": $api_admin_bulk_import,
    "./routes/api/admin/challenges.ts": $api_admin_challenges,
    "./routes/api/admin/check-admins.ts": $api_admin_check_admins,
    "./routes/api/admin/classrooms.ts": $api_admin_classrooms,
    "./routes/api/admin/delete-cache.ts": $api_admin_delete_cache,
    "./routes/api/admin/force-promote.ts": $api_admin_force_promote,
    "./routes/api/admin/migrate-users.ts": $api_admin_migrate_users,
    "./routes/api/admin/parent-associations.ts": $api_admin_parent_associations,
    "./routes/api/admin/promote-first.ts": $api_admin_promote_first,
    "./routes/api/admin/quota-stats.ts": $api_admin_quota_stats,
    "./routes/api/admin/schools.ts": $api_admin_schools,
    "./routes/api/admin/send-invite.ts": $api_admin_send_invite,
    "./routes/api/admin/usage.ts": $api_admin_usage,
    "./routes/api/admin/users.ts": $api_admin_users,
    "./routes/api/admin/validate-cache.ts": $api_admin_validate_cache,
    "./routes/api/admin/verify-parent.ts": $api_admin_verify_parent,
    "./routes/api/auth/callback.ts": $api_auth_callback,
    "./routes/api/auth/complete-setup.ts": $api_auth_complete_setup,
    "./routes/api/auth/delegate-signup.ts": $api_auth_delegate_signup,
    "./routes/api/auth/forgot-password.ts": $api_auth_forgot_password,
    "./routes/api/auth/google/login.ts": $api_auth_google_login,
    "./routes/api/auth/login.ts": $api_auth_login,
    "./routes/api/auth/logout.ts": $api_auth_logout,
    "./routes/api/auth/parent-signup.ts": $api_auth_parent_signup,
    "./routes/api/auth/parent-student-verification.ts":
      $api_auth_parent_student_verification,
    "./routes/api/auth/resend-verification.ts": $api_auth_resend_verification,
    "./routes/api/auth/reset-password.ts": $api_auth_reset_password,
    "./routes/api/auth/signup.ts": $api_auth_signup,
    "./routes/api/auth/teacher-signup.ts": $api_auth_teacher_signup,
    "./routes/api/auth/update-password.ts": $api_auth_update_password,
    "./routes/api/auth/verify.ts": $api_auth_verify,
    "./routes/api/challenges/submit.ts": $api_challenges_submit,
    "./routes/api/classroom/add.ts": $api_classroom_add,
    "./routes/api/classroom/backup-to-sheet.ts": $api_classroom_backup_to_sheet,
    "./routes/api/classroom/claim.ts": $api_classroom_claim,
    "./routes/api/classroom/export.ts": $api_classroom_export,
    "./routes/api/classroom/move-books.ts": $api_classroom_move_books,
    "./routes/api/classroom/remove.ts": $api_classroom_remove,
    "./routes/api/classroom/update-quantity.ts": $api_classroom_update_quantity,
    "./routes/api/debug/list-keys.ts": $api_debug_list_keys,
    "./routes/api/debug/me.ts": $api_debug_me,
    "./routes/api/debug/my-books.ts": $api_debug_my_books,
    "./routes/api/debug/restore-school.ts": $api_debug_restore_school,
    "./routes/api/debug/user-by-email.ts": $api_debug_user_by_email,
    "./routes/api/delegates/invite-teacher.ts": $api_delegates_invite_teacher,
    "./routes/api/delegates/list.ts": $api_delegates_list,
    "./routes/api/delegates/remove.ts": $api_delegates_remove,
    "./routes/api/invitations/accept.ts": $api_invitations_accept,
    "./routes/api/invitations/create.ts": $api_invitations_create,
    "./routes/api/invitations/list.ts": $api_invitations_list,
    "./routes/api/invitations/revoke.ts": $api_invitations_revoke,
    "./routes/api/lookup.ts": $api_lookup,
    "./routes/api/school-admin/staff-import.ts": $api_school_admin_staff_import,
    "./routes/api/schools.ts": $api_schools,
    "./routes/api/settings/update-school.ts": $api_settings_update_school,
    "./routes/api/settings/update-sheet-url.ts": $api_settings_update_sheet_url,
    "./routes/api/students/claim.ts": $api_students_claim,
    "./routes/api/teachers/list.ts": $api_teachers_list,
    "./routes/auth/callback.ts": $auth_callback,
    "./routes/challenge-book.tsx": $challenge_book,
    "./routes/challenge-books.tsx": $challenge_books,
    "./routes/claim-classroom.tsx": $claim_classroom,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/delegate-request.tsx": $delegate_request,
    "./routes/delegate-signup.tsx": $delegate_signup,
    "./routes/forgot-password.tsx": $forgot_password,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.ts": $logout,
    "./routes/parent-dashboard.tsx": $parent_dashboard,
    "./routes/parent-signup.tsx": $parent_signup,
    "./routes/parent/claim-students.tsx": $parent_claim_students,
    "./routes/reset-password.tsx": $reset_password,
    "./routes/school-admin/staff-import/index.tsx":
      $school_admin_staff_import_index,
    "./routes/select-classroom.tsx": $select_classroom,
    "./routes/settings.tsx": $settings,
    "./routes/setup.tsx": $setup,
    "./routes/signup.tsx": $signup,
    "./routes/teacher-signup.tsx": $teacher_signup,
    "./routes/verify.tsx": $verify,
  },
  islands: {
    "./islands/AdminHeader.tsx": $AdminHeader,
    "./islands/App.tsx": $App,
    "./islands/BarcodeScanner.tsx": $BarcodeScanner,
    "./islands/BulkImport.tsx": $BulkImport,
    "./islands/ChallengeForm.tsx": $ChallengeForm,
    "./islands/ChallengeReview.tsx": $ChallengeReview,
    "./islands/ClaimClassroom.tsx": $ClaimClassroom,
    "./islands/ClassroomBrowser.tsx": $ClassroomBrowser,
    "./islands/DashboardContent.tsx": $DashboardContent,
    "./islands/DelegateRequestForm.tsx": $DelegateRequestForm,
    "./islands/DelegateSignupForm.tsx": $DelegateSignupForm,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/MultipleChallengeForm.tsx": $MultipleChallengeForm,
    "./islands/ParentDashboard.tsx": $ParentDashboard,
    "./islands/ParentSignupForm.tsx": $ParentSignupForm,
    "./islands/ParentVerification.tsx": $ParentVerification,
    "./islands/PublicClassroom.tsx": $PublicClassroom,
    "./islands/QuotaMonitor.tsx": $QuotaMonitor,
    "./islands/ScanHistory.tsx": $ScanHistory,
    "./islands/SchoolCatalog.tsx": $SchoolCatalog,
    "./islands/SchoolManagement.tsx": $SchoolManagement,
    "./islands/SettingsPanel.tsx": $SettingsPanel,
    "./islands/SetupForm.tsx": $SetupForm,
    "./islands/SignupForm.tsx": $SignupForm,
    "./islands/StaffImport.tsx": $StaffImport,
    "./islands/StudentClaimForm.tsx": $StudentClaimForm,
    "./islands/TeacherSignupForm.tsx": $TeacherSignupForm,
    "./islands/UsageStats.tsx": $UsageStats,
    "./islands/UserManagement.tsx": $UserManagement,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
