// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_auth_login from "./routes/api/auth/login.ts";
import * as $api_auth_logout from "./routes/api/auth/logout.ts";
import * as $api_auth_signup from "./routes/api/auth/signup.ts";
import * as $api_auth_verify from "./routes/api/auth/verify.ts";
import * as $api_lookup from "./routes/api/lookup.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $settings from "./routes/settings.tsx";
import * as $signup from "./routes/signup.tsx";
import * as $verify from "./routes/verify.tsx";
import * as $App from "./islands/App.tsx";
import * as $BarcodeScanner from "./islands/BarcodeScanner.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $ScanHistory from "./islands/ScanHistory.tsx";
import * as $SettingsPanel from "./islands/SettingsPanel.tsx";
import * as $SignupForm from "./islands/SignupForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/auth/login.ts": $api_auth_login,
    "./routes/api/auth/logout.ts": $api_auth_logout,
    "./routes/api/auth/signup.ts": $api_auth_signup,
    "./routes/api/auth/verify.ts": $api_auth_verify,
    "./routes/api/lookup.ts": $api_lookup,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/settings.tsx": $settings,
    "./routes/signup.tsx": $signup,
    "./routes/verify.tsx": $verify,
  },
  islands: {
    "./islands/App.tsx": $App,
    "./islands/BarcodeScanner.tsx": $BarcodeScanner,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/ScanHistory.tsx": $ScanHistory,
    "./islands/SettingsPanel.tsx": $SettingsPanel,
    "./islands/SignupForm.tsx": $SignupForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
